### ISSUE TITLE
Build error for Node.js 16 on MacOS

### ISSUE THREAD

**Issue by bkimminich** [marudor/libxmljs2#123]
The following error occurs when using this module with Node.js 16.x in a GitHub action running on `macos-latest`:

```
npm ERR! code 1
npm ERR! path /Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --loglevel http
npm ERR! CXX(target) Release/obj.target/xmljs/src/libxmljs.o
npm ERR! Failed to execute '/Users/runner/hostedtoolcache/node/16.6.1/x64/bin/node /Users/runner/hostedtoolcache/node/16.6.1/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.26.7/node-v93-darwin-x64-unknown.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/marudor/libxmljs2/releases/download/v0.26.7/node-v93-darwin-x64-unknown.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for libxmljs2@0.26.7 and node@16.6.1 (node-v93 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/marudor/libxmljs2/releases/download/v0.26.7/node-v93-darwin-x64-unknown.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.6.1 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp http GET https://nodejs.org/download/release/v16.6.1/node-v16.6.1-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.6.1/node-v16.6.1-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.6.1/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.6.1/SHASUMS256.txt
npm ERR! (node:1286) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
npm ERR! In file included from ../src/libxmljs.cc:3:
npm ERR! In file included from /Users/runner/Library/Caches/node-gyp/16.6.1/include/node/v8.h:30:
npm ERR! /Users/runner/Library/Caches/node-gyp/16.6.1/include/node/v8-internal.h:488:38: error: no template named 'remove_cv_t' in namespace 'std'; did you mean 'remove_cv'?
npm ERR!             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
npm ERR!                                 ~~~~~^~~~~~~~~~~
npm ERR!                                      remove_cv
npm ERR! /Applications/Xcode_12.4.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/type_traits:697:50: note: 'remove_cv' declared here
npm ERR! template <class _Tp> struct _LIBCPP_TEMPLATE_VIS remove_cv
npm ERR!                                                  ^
npm ERR! 1 error generated.
npm ERR! make: *** [Release/obj.target/xmljs/src/libxmljs.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/runner/hostedtoolcache/node/16.6.1/x64/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Darwin 19.6.0
npm ERR! gyp ERR! command "/Users/runner/hostedtoolcache/node/16.6.1/x64/bin/node" "/Users/runner/hostedtoolcache/node/16.6.1/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--loglevel=http" "--module=/Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2/build/Release/xmljs.node" "--module_name=xmljs" "--module_path=/Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2
npm ERR! gyp ERR! node -v v16.6.1
npm ERR! gyp ERR! node-gyp -v v7.1.2
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/Users/runner/hostedtoolcache/node/16.6.1/x64/bin/node /Users/runner/hostedtoolcache/node/16.6.1/x64/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --loglevel=http --module=/Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2/build/Release/xmljs.node --module_name=xmljs --module_path=/Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/runner/work/juice-shop/juice-shop/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:394:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! node-pre-gyp ERR! System Darwin 19.6.0
npm ERR! node-pre-gyp ERR! command "/Users/runner/hostedtoolcache/node/16.6.1/x64/bin/node" "/Users/runner/work/juice-shop/juice-shop/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--loglevel" "http"
npm ERR! node-pre-gyp ERR! cwd /Users/runner/work/juice-shop/juice-shop/node_modules/libxmljs2
npm ERR! node-pre-gyp ERR! node -v v16.6.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.5
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/runner/.npm/_logs/2021-08-10T10_11_22_922Z-debug.log
```

On Windows- and Linux-based GH actions it passes the build. See https://github.com/bkimminich/juice-shop/actions/runs/1116145356 for example. On Node.js 12-15 everything works fine with MacOS as well.

**Comment by marudor** [comment]
This is not a problem with libxmljs2.
I'm building it on github with macos-10.15 (which is equal to macos-latest)
