### ISSUE TITLE
version 0.32.0 on nodejs 18 - cannot run on environment for AWS lambda (glibc 2.26)

### ISSUE THREAD

**Issue by sundysea2018** [marudor/libxmljs2#196]
version 0.32.0 on nodejs 18 - cannot run on environment for AWS lambda (glibc 2.26)

2023-06-12T08:21:53.022Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Error",
    "errorMessage": "/lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/task/node_modules/libxmljs2/build/Release/xmljs.node)",
    "code": "ERR_DLOPEN_FAILED",
    "stack": [
        "Error: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/task/node_modules/libxmljs2/build/Release/xmljs.node)",
        "    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)",
        "    at Module.load (node:internal/modules/cjs/loader:1117:32)",
        "    at Module._load (node:internal/modules/cjs/loader:958:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1141:19)",
        "    at require (node:internal/modules/cjs/helpers:110:18)",
        "    at bindings (/var/task/node_modules/bindings/bindings.js:112:48)",
        "    at Object.<anonymous> (/var/task/node_modules/libxmljs2/lib/bindings.js:1:37)",
        "    at Module._compile (node:internal/modules/cjs/loader:1254:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1117:32)",
        "    at Module._load (node:internal/modules/cjs/loader:958:12)",
        "    at Module.require (node:internal/modules/cjs/loader:1141:19)",
        "    at require (node:internal/modules/cjs/helpers:110:18)",
        "    at Object.<anonymous> (/var/task/node_modules/libxmljs2/index.js:4:18)",
        "    at Module._compile (node:internal/modules/cjs/loader:1254:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)"
    ]
}

**Comment by magickspell** [comment]
I have the same issue on Docker container (node:16.14-slim) with glibc 2.28 on board.
The decision is to update glibc to 2.29, something like that:
```
sudo apt-get install gawk bison -y
wget -c https://ftp.gnu.org/gnu/glibc/glibc-2.29.tar.gz
tar -zxvf glibc-2.29.tar.gz && cd glibc-2.29
mkdir glibc-build && cd glibc-build
../configure --prefix=/opt/glibc-2.29
make 
sudo make install
```

**Comment by shopsinc** [comment]
I have not been able to get this to work either. I thought maybe if I used an amazon linux container to build and deploy from it would work but that had the same problems.

**Comment by shopsinc** [comment]
I'm having the same problem. I also attempted to build libxmljs2 in an amazonlinux2023 and could not get that to work either.

**Comment by cebrakadabra** [comment]
in docker `FROM node:16.3` works. The background to all of this is, that node uses similar release names as debian does. E.g. if you look at https://packages.debian.org/bullseye/libc6 (top right) you will see `bullseye`, `bookworm`, etc. If you run:
```sh
docker run -ti --entrypoint=/bin/bash {TAG_ID}
```
followed by `ldd --version` you can see which libc version your docker container uses. Each nodejs version is tied to a specific libc version - as it is harder to influence the lambda runtime (in my case) i decided to look for the node version that links to the correct libc version required. It's an intermediate solution, but I could not get it working under node:18 due to the limitations of the lambda runtime. Hope this helps!

**Comment by cebrakadabra** [comment]
Secondly I was exploring adding libc as a lambda layer, but wasn't satisfied with that path, as I don't think it would work, as in my docker container, the lib is being built against a certain runtime - hence the limitation and my above answer to be my successful path
