### ISSUE TITLE
Error in xmljs.node on node.js 12.3.0

### ISSUE THREAD

**Issue by bkimminich** [marudor/libxmljs2#4]
```
(node:14364) UnhandledPromiseRejectionWarning: Error: Die angegebene Prozedur wurde nicht gefunden.
\\?\C:\Data\GitHub\juice-shop\node_modules\libxmljs2\build\Release\xmljs.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:815:18)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at bindings (C:\Data\GitHub\juice-shop\node_modules\bindings\bindings.js:112:48)
    at Object.<anonymous> (C:\Data\GitHub\juice-shop\node_modules\libxmljs2\lib\bindings.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:681:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\Data\GitHub\juice-shop\node_modules\libxmljs2\index.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
(node:14364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bkimminich** [comment]
This happens on my Windows 10 machine. Will add log of Travis-CI for Linux, MaxOS and Windows in case they behave differently.

**Comment by bkimminich** [comment]
During `npm install` all looks okay `libxmljs2`-wise:
```
> libxmljs2@0.21.3 install C:\Data\GitHub\juice-shop\node_modules\libxmljs2
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.21.3/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp http 200 https://github.com/marudor/libxmljs2/releases/download/v0.21.3/node-v72-win32-x64-unknown.tar.gz
[libxmljs2] Success: "C:\Data\GitHub\juice-shop\node_modules\libxmljs2\build\Release\xmljs.node" is installed via remote
```

The above error occurs when running `npm start`. Feel free to use https://github.com/bkimminich/juice-shop/commit/4a5b6f70adb06d14d8f37d6b8881f1072515e639 to reproduce.

**Comment by bkimminich** [comment]
Problem just vanished after I deleted `node_modules` entirely before `npm install` with 12.x ... 👑

**Comment by xprudhomme** [comment]
Can we please re-open this "Error in xmljs.node" issue ?

I am facing it, even after deleting the `node_modules` folder, and doing `npm install` with Node 12.x ...

```
renderer.js:476 Error: Specified procedure could not be found.
\\?\C:\GitHub\alliance-electron\node_modules\libxmljs2\build\Release\xmljs.node
    at process.func (electron/js2c/asar.js:140)
    at process.func [as dlopen] (electron/js2c/asar.js:140)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016)
    at Object.func (electron/js2c/asar.js:140)
    at Object.func [as .node] (electron/js2c/asar.js:140)
    at Module.load (internal/modules/cjs/loader.js:816)
    at Module._load (internal/modules/cjs/loader.js:728)
    at Module._load (electron/js2c/asar.js:717)
    at Function.Module._load (electron/js2c/asar.js:717)
    at Module.require (internal/modules/cjs/loader.js:853)
```

Here is a snippet from console logs when running `npm i --save` command

```
> libxmljs2@0.25.0 install C:\GitHub\alliance-electron\node_modules\libxmljs2
> node-pre-gyp install --fallback-to-build --loglevel http

node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp http GET https://github.com/marudor/libxmljs2/releases/download/v0.25.0/node-v72-win32-x64-unknown.tar.gz
node-pre-gyp http 200 https://github.com/marudor/libxmljs2/releases/download/v0.25.0/node-v72-win32-x64-unknown.tar.gz
[libxmljs2] Success: "C:\GitHub\alliance-electron\node_modules\libxmljs2\build\Release\xmljs.node" is installed via remote
```

However, I have no idea why my console displays `\\?` right after "could not be found" and before `C:\GitHub\alliance-electron\node_modules\libxmljs2\build\Release\xmljs.node`

Could it be related to Electron?

Node v12.16.1
Electron 8.2.0

Npm package.json dependencies:
```
 "dependencies": {
    "bootstrap": "^4.4.1",
    "electron-squirrel-startup": "^1.0.0",
    "keytar": "^5.4.0",
    "libxmljs2": "^0.25.0",
    "node-fetch": "^2.6.0",
    "parse5": "^5.1.1",
    "xmlserializer": "^0.6.1"
  },
  "devDependencies": {
    "@electron-forge/cli": "^6.0.0-beta.50",
    "@electron-forge/maker-deb": "^6.0.0-beta.50",
    "@electron-forge/maker-rpm": "^6.0.0-beta.50",
    "@electron-forge/maker-squirrel": "^6.0.0-beta.50",
    "@electron-forge/maker-zip": "^6.0.0-beta.50",
    "electron": "8.2.0"
  }
```
